---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


## Loading and preprocessing the data

```{r, echo = TRUE}
data1 <- read.csv("activity.csv", header = TRUE, stringsAsFactors = FALSE, na.strings = "NA")
#Convert the date from character to a Date format
data1$date <- as.Date(data1$date, "%Y-%m-%d")

#Histogram of total steps taken each day

sum_agg <- aggregate(steps ~ date, data1[!is.na(data1$steps),], FUN = sum)
barplot(sum_agg$steps, width = 1, names.arg = sum_agg$date, space = 0, main = "Total Steps taken each day", xlab = "Steps")

```

## What is mean total number of steps taken per day?

```{r, echo = TRUE}
#Mean of the total steps taken each day
mean_agg <- aggregate(steps ~ date, data1, mean, na.rm = TRUE)
print(mean_agg)
```

``` {r, echo = TRUE}
#Median of the totoal steps taken each day
median_agg <- aggregate(steps ~ date, sum_agg, median)
print(median_agg)
#Time series plot of mean steps taken per day
with(mean_agg, plot(date, steps, type = "l"))
```


## What is the average daily activity pattern?
``` {r, echo = TRUE}
#Compute the 5-minute interval that, on average, contains maximum number of steps
sum_steps <- aggregate(steps ~ interval, data1[!is.na(data1$steps),], FUN = sum)
print(sum_steps[order(sum_steps$steps, decreasing = TRUE),][1,])

```

## Imputing missing values
``` {r, echo = TRUE}

#Imputing Missing values
#Identify which rows have NA values for steps
val <- is.na(data1$steps)
#data1[val,]
#The NA will be replaced by the mean value of the steps in that time interval

mean_steps <- aggregate(steps ~ interval, data1[!is.na(data1$steps),], FUN = mean)
data1[val, 1] <- mean_steps[match(data1[val, 3], mean_steps$interval), 2]

#Hisatogram of total steps taken each day
sum_agg <- aggregate(steps ~ date, data1[!is.na(data1$steps),], FUN = sum)
barplot(sum_agg$steps, width = 1, names.arg = sum_agg$date, space = 0, main = "Total Steps taken each day", xlab = "Steps")

#Mean of the total steps taken each day
mean_agg <- aggregate(steps ~ date, data1, mean)
print(mean_agg)

median_agg <- aggregate(steps ~ date, sum_agg, median)
print(median_agg)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}

weekday <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
data1$dayname <- factor((weekdays(data1$date) %in% weekday), 
                        levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

par(mfrow = c(2,1))

mean_weekday <- aggregate(steps ~ interval, data1[data1$dayname == "weekday",], FUN = mean)
with(mean_weekday, plot(interval, steps, type = "l"))

mean_weekend <- aggregate(steps ~ interval, data1[data1$dayname == "weekend",], FUN = mean)
with(mean_weekend, plot(interval, steps, type = "l"))

```